### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rofl0r** [hoglet67/Z80Decoder#1]
hello, i've come across this repo looking for the "perfect z80" emulator that was mentioned here: https://stardot.org.uk/forums/viewtopic.php?p=349760#p349760
even though this repo does not appear to be that specific emulator, the one you've written here seems to be pretty useful to compare with the emulator i'm working on to find the correct behaviour for cornercases.

unfortunately, i couldn't find any license text which means the code is currently not usable by anyone:  https://choosealicense.com/no-permission/

i hope you consider to add a license, preferably a permissive one such as MIT.

**Comment by hoglet67** [comment]
I've added a GPL v3 License file.

**Comment by hoglet67** [comment]
FYI, the "Perfect Z80" emulator is a Z80 branch of Perfect6502 and can be found here:
https://github.com/hoglet67/perfect6502/tree/Z80
